cats_auth/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  root to: redirect('/cats')
  
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

cats_auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>C A T S <3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    
    <ul id="navbar">
      <% if !current_user %>
      <form action="<%= new_session_url %>" method="get">
        <input type="hidden"
               name="authenticity_token"
              value="<%= form_authenticity_token %>">
        <input type="submit" name="" value="Login">
      </form>
      <form action="<%= new_user_url %>" method="get">
        <input type="hidden"
               name="authenticity_token"
              value="<%= form_authenticity_token %>">
        <input type="submit" name="" value="Sign Up">
      </form>
      <% else %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden"
               name="authenticity_token"
              value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Log Out">
      </form>
      <% end %>
      <form action="<%= cats_url %>" method="get">
        <input type="hidden"
               name="authenticity_token"
              value="<%= form_authenticity_token %>">
        <input type="submit" value="Go Back to Homepage">
      </form>
    </ul>

    <%= yield %>
  </body>
</html>